# fly.toml app configuration file generated for frozen-einstein-webring

app = "asadaame5121-webring"
primary_region = "nrt"
kill_timeout = 10

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = "suspend"
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]



[env]
  PORT = "8080"

  PUBLIC_URL = "https://at-circle.asadaame5121.net"
  BSKY_SERVICE_URL = "https://bsky.social"
  CLIENT_NAME = "at-circle"
  NODE_ENV = "production"
